# Generated by Django 4.2.16 on 2024-10-28 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('instructions', djrichtextfield.models.RichTextField(max_length=10000)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='recipes/')),
                ('image_alt', models.CharField(max_length=100)),
                ('prep_time', models.IntegerField(default='15')),
                ('cook_time', models.IntegerField(default='40')),
                ('serves', models.IntegerField(choices=[('2', 'Two'), ('4', 'Four'), ('6', 'Six'), ('8', 'Eight'), ('10', 'Ten')], default='2')),
                ('posted_date', models.DateTimeField(auto_now=True)),
                ('lowsugar', models.BooleanField()),
                ('glutenfree', models.BooleanField()),
                ('dairyfree', models.BooleanField()),
                ('vegan', models.BooleanField()),
                ('vegitarian', models.BooleanField()),
                ('highfiber', models.BooleanField()),
                ('highprotein', models.BooleanField()),
                ('nutfree', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
    ]
