# Generated by Django 4.2.16 on 2024-10-28 06:08

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=djrichtextfield.models.RichTextField(
                default="Ingredients", max_length=10000
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=djrichtextfield.models.RichTextField(
                default="Instructions", max_length=10000
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="serves",
            field=models.IntegerField(
                choices=[(2, "2"), (4, "4"), (6, "6"), (8, "8"), (10, "10")],
                default="2",
            ),
        ),
    ]
